version: '3'
services:
  postgres:
    image: 'postgres:10.1'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
    network_mode: host
    volumes:
      - "/home/ps/data/pgdata:/var/lib/postgresql/data"
  data_loader:
    build: 'app'
    volumes:
      - "/home/ps/data/crypto-currency-pairs-at-minute-resolution:/data"
      - "./app:/app"
    command: "echo dummy" # "python3 -u /app/main.py"  #
    environment:
      in_path: /data
      out_path: /data/dump.csv
      selected: absusd,abseth
      host: localhost
      PGDATA: /var/lib/postgresql/data/pgdata
      past_factor: 10
    network_mode: host
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
    network_mode: host
    volumes:
      - "/home/ps/data/redis:/data"
    command: "redis-server --appendonly yes --maxmemory 5gb"

